package Frm_Activity_SubMenu;

import Commons.TextPlaceholder;
import Commons.TxtBoxSpace;
import Controller.ActivityController;
import JDialogCustom.ErrorYes_NoJDialog;
import JDialogCustom.SuccessJDialog;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author world
 */
public class SubMenuOfUnits extends javax.swing.JPanel {

    TextPlaceholder placeHolder = new TextPlaceholder();
    TxtBoxSpace txtBoxSpaceing = new TxtBoxSpace();

    ActivityController activityController = new ActivityController();
    
    String txtUnitName1 = "Type Unit Name";

    /**
     * Creates new form SubMenuOfUnits
     */
    public SubMenuOfUnits() {
        initComponents();
        activityController.AllUnit(jTableUnits);
    }

    private void clearAll() {
        txtUnitName.setText(txtUnitName1);
        jComboBoxUnitStatus.setSelectedIndex(0);
        btnSubmit1.setText("Submit");

        lb_unit_id.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtUnitName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        panelDropDown = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxUnitStatus = new javax.swing.JComboBox<>();
        btnClean = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUnits = new javax.swing.JTable();
        lb_unit_id = new javax.swing.JLabel();
        btnSubmit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel10.setBackground(new java.awt.Color(248, 248, 248));
        jPanel10.setBorder(null);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUnitName.setForeground(new java.awt.Color(78, 78, 78));
        txtUnitName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnitName.setText("Type Unit Name");
        txtUnitName.setBorder(null);
        txtUnitName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnitNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnitNameFocusLost(evt);
            }
        });
        jPanel4.add(txtUnitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(115, 135, 156));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Unit Name:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 80, 30));

        jPanel10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, -1));

        panelDropDown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(115, 135, 156));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Status:");
        panelDropDown.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 30));

        jComboBoxUnitStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "InActive" }));
        panelDropDown.add(jComboBoxUnitStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 30));

        jPanel10.add(panelDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        btnClean.setBackground(new java.awt.Color(49, 147, 0));
        btnClean.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClean.setForeground(new java.awt.Color(250, 255, 255));
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jPanel10.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTableUnits.setForeground(new java.awt.Color(78, 78, 78));
        jTableUnits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Unit Name", "Status", "/", "X"
            }
        ));
        jTableUnits.setRowHeight(25);
        jTableUnits.getTableHeader().setReorderingAllowed(false);
        jTableUnits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUnitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUnits);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 710, 400));

        lb_unit_id.setText("ID");
        jPanel10.add(lb_unit_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 100, -1));

        btnSubmit1.setBackground(new java.awt.Color(49, 147, 0));
        btnSubmit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit1.setForeground(new java.awt.Color(250, 255, 255));
        btnSubmit1.setText("Submit");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });
        jPanel10.add(btnSubmit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitNameFocusGained
        placeHolder.placeHolder(txtUnitName1, txtUnitName);
    }//GEN-LAST:event_txtUnitNameFocusGained

    private void txtUnitNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitNameFocusLost
        placeHolder.placeHolder(txtUnitName1, txtUnitName);
    }//GEN-LAST:event_txtUnitNameFocusLost

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        clearAll();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jTableUnitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUnitsMouseClicked
        if (evt.getClickCount() == 1) {
            btnSubmit1.setText("Update");
        }
        int row = jTableUnits.getSelectedRow();
        String id = jTableUnits.getModel().getValueAt(row, 0).toString();
        try {
            List list = activityController.EditUnitData(id);

            lb_unit_id.setText(list.get(0).toString());
            txtUnitName.setText(list.get(1).toString());
            jComboBoxUnitStatus.setSelectedItem(list.get(2));
        } catch (Exception e) {
            System.out.println(e);
        }

        if (SwingUtilities.isRightMouseButton(evt)) {
            ErrorYes_NoJDialog er = new ErrorYes_NoJDialog(null, true, id, "units");
            er.setVisible(true);
        }
    }//GEN-LAST:event_jTableUnitsMouseClicked

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        if (btnSubmit1.getText().equals("Update")) {
            String id = lb_unit_id.getText();
            String color_code = lb_unit_id.getText();
            String color_name = txtUnitName.getText();
            String status = jComboBoxUnitStatus.getSelectedItem().toString();
            if (activityController.updateUnit(id, color_name, status) == true) {
                SuccessJDialog er = new SuccessJDialog(null, true);
                er.setVisible(true);
                clearAll();
            }

            activityController.AllUnit(jTableUnits);

        } else if (btnSubmit1.getText().equals("Submit")) {
            String unit_name = txtUnitName.getText();
            String status = jComboBoxUnitStatus.getSelectedItem().toString();
            if (activityController.addUnit(unit_name, status) == true) {
                SuccessJDialog er = new SuccessJDialog(null, true);
                er.setVisible(true);
            } else {
                SuccessJDialog er = new SuccessJDialog(null, true);
                er.setVisible(true);
            }
            clearAll();
            activityController.AllUnit(jTableUnits);

        }
    }//GEN-LAST:event_btnSubmit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSubmit1;
    public javax.swing.JComboBox<String> jComboBoxUnitStatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableUnits;
    private javax.swing.JLabel lb_unit_id;
    private javax.swing.JPanel panelDropDown;
    private javax.swing.JTextField txtUnitName;
    // End of variables declaration//GEN-END:variables
}
