/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posdesign;

import Commons.PanelController;
import Frm_products.SubMenuOfActivity;
import Frm_products.SubMenuOfProducts;
import Frm_products.SubMenuOfPurchase;

import java.awt.Color;

/**
 *
 * @author Niklaus
 */
public class Main2Frame extends javax.swing.JFrame {

    SubMenuOfProducts subMenuOfProducts = new SubMenuOfProducts();
    PanelController panelVisibleController = new PanelController();

    /**
     * Creates new form Main2Frame
     */
    public Main2Frame() {
        initComponents();
        products();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelProduct = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnProducts = new javax.swing.JButton();
        panelPurchase = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();
        panelSales = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnSales = new javax.swing.JButton();
        panelStore = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelAccounting = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelUsers = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        panelReport1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnPurchase1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        panelDisplay = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Biz Radix");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27))
        );

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        panelProduct.setBackground(new java.awt.Color(0, 51, 153));
        panelProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProductMouseClicked(evt);
            }
        });
        panelProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelProductKeyPressed(evt);
            }
        });
        panelProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8basket.png"))); // NOI18N
        panelProduct.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        btnProducts.setBackground(new java.awt.Color(0, 51, 153));
        btnProducts.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnProducts.setForeground(java.awt.Color.white);
        btnProducts.setText("Products");
        btnProducts.setAlignmentY(0.0F);
        btnProducts.setBorder(null);
        btnProducts.setBorderPainted(false);
        btnProducts.setContentAreaFilled(false);
        btnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        btnProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnProductsKeyPressed(evt);
            }
        });
        panelProduct.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 40));

        panelPurchase.setBackground(new java.awt.Color(0, 51, 153));
        panelPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPurchaseMouseClicked(evt);
            }
        });
        panelPurchase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8purchases.png"))); // NOI18N
        panelPurchase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        btnPurchase.setBackground(new java.awt.Color(0, 51, 153));
        btnPurchase.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnPurchase.setForeground(java.awt.Color.white);
        btnPurchase.setText("Purchase");
        btnPurchase.setAlignmentY(0.0F);
        btnPurchase.setBorder(null);
        btnPurchase.setBorderPainted(false);
        btnPurchase.setContentAreaFilled(false);
        btnPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPurchase.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });
        btnPurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPurchaseKeyPressed(evt);
            }
        });
        panelPurchase.add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 40));

        panelSales.setBackground(new java.awt.Color(0, 51, 153));
        panelSales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelSalesKeyPressed(evt);
            }
        });
        panelSales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/iconsSales_24.png"))); // NOI18N
        panelSales.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        btnSales.setBackground(new java.awt.Color(0, 51, 153));
        btnSales.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnSales.setForeground(java.awt.Color.white);
        btnSales.setText("Sales");
        btnSales.setAlignmentY(0.0F);
        btnSales.setBorder(null);
        btnSales.setBorderPainted(false);
        btnSales.setContentAreaFilled(false);
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        btnSales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalesKeyPressed(evt);
            }
        });
        panelSales.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 40));

        panelStore.setBackground(new java.awt.Color(0, 51, 153));
        panelStore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8-shop-24.png"))); // NOI18N
        panelStore.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Stores");
        panelStore.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 40));

        panelAccounting.setBackground(new java.awt.Color(0, 51, 153));
        panelAccounting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8-accounting24.png"))); // NOI18N
        panelAccounting.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Accounting");
        panelAccounting.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, 40));

        panelUsers.setBackground(new java.awt.Color(0, 51, 153));
        panelUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8-user-24.png"))); // NOI18N
        panelUsers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Users");
        panelUsers.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 40));

        panelReport.setBackground(new java.awt.Color(0, 51, 153));
        panelReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8-report-24.png"))); // NOI18N
        panelReport.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Reports");
        panelReport.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, 40));

        panelReport1.setBackground(new java.awt.Color(0, 51, 153));
        panelReport1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8-report-24.png"))); // NOI18N
        panelReport1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        btnPurchase1.setBackground(new java.awt.Color(0, 51, 153));
        btnPurchase1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnPurchase1.setForeground(java.awt.Color.white);
        btnPurchase1.setText("Activity");
        btnPurchase1.setAlignmentY(0.0F);
        btnPurchase1.setBorder(null);
        btnPurchase1.setBorderPainted(false);
        btnPurchase1.setContentAreaFilled(false);
        btnPurchase1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPurchase1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPurchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchase1ActionPerformed(evt);
            }
        });
        btnPurchase1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPurchase1KeyPressed(evt);
            }
        });
        panelReport1.add(btnPurchase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 160, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addComponent(panelPurchase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAccounting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(panelReport1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStore, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("We are problem solver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrollPane1.setBackground(new java.awt.Color(78, 132, 240));

        panelDisplay.setBackground(new java.awt.Color(254, 254, 254));
        panelDisplay.setLayout(new java.awt.CardLayout());
        scrollPane1.add(panelDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
//        int x = evt.getXOnScreen();
//        int y = evt.getYOnScreen();
//        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
//        xx = evt.getX();
//        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void panelProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductMouseClicked
        products();
    }//GEN-LAST:event_panelProductMouseClicked

    private void products() {
        panelProduct.setBackground(new Color(0, 0, 255));
        panelPurchase.setBackground(new Color(0, 51, 153));
        panelSales.setBackground(new Color(0, 51, 153));
        panelAccounting.setBackground(new Color(0, 51, 153));
        panelStore.setBackground(new Color(0, 51, 153));
        panelUsers.setBackground(new Color(0, 51, 153));
        panelReport.setBackground(new Color(0, 51, 153));

        panelVisibleController.showPanelWindow(new SubMenuOfProducts());
    }
    private void panelPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPurchaseMouseClicked
        Purchase();
    }//GEN-LAST:event_panelPurchaseMouseClicked
    private void Purchase() {
        panelProduct.setBackground(new Color(0, 51, 153));
        panelPurchase.setBackground(new Color(0, 0, 255));
        panelSales.setBackground(new Color(0, 51, 153));
        panelAccounting.setBackground(new Color(0, 51, 153));
        panelStore.setBackground(new Color(0, 51, 153));
        panelUsers.setBackground(new Color(0, 51, 153));
        panelReport.setBackground(new Color(0, 51, 153));

        panelVisibleController.showPanelWindow(new SubMenuOfPurchase());
    }
    private void panelProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelProductKeyPressed

    }//GEN-LAST:event_panelProductKeyPressed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        products();
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        Purchase();
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnPurchaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPurchaseKeyPressed
        if (evt.getKeyCode() == evt.VK_DOWN) {
            Purchase();
            sales();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            products();
            btnProducts.requestFocus();
        }
    }//GEN-LAST:event_btnPurchaseKeyPressed

    private void btnProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProductsKeyPressed
        if (evt.getKeyCode() == evt.VK_DOWN) {
            Purchase();
            btnPurchase.requestFocus();
        }


    }//GEN-LAST:event_btnProductsKeyPressed

    private void btnSalesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalesKeyPressed
        if (evt.getKeyCode() == evt.VK_UP) {
            Purchase();
            btnPurchase.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            sales();
            btnSales.requestFocus();
        }
    }//GEN-LAST:event_btnSalesKeyPressed

    private void panelSalesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelSalesKeyPressed
        if (evt.getKeyCode() == evt.VK_UP) {
            Purchase();
            btnPurchase.requestFocus();
        }
    }//GEN-LAST:event_panelSalesKeyPressed

    private void btnPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchase1ActionPerformed
       Activity();
    }//GEN-LAST:event_btnPurchase1ActionPerformed
    private void Activity() {
        panelProduct.setBackground(new Color(0, 51, 153));
        panelPurchase.setBackground(new Color(0, 0, 255));
        panelSales.setBackground(new Color(0, 51, 153));
        panelAccounting.setBackground(new Color(0, 51, 153));
        panelStore.setBackground(new Color(0, 51, 153));
        panelUsers.setBackground(new Color(0, 51, 153));
        panelReport.setBackground(new Color(0, 51, 153));

        panelVisibleController.showPanelWindow(new SubMenuOfActivity());
    }
    private void btnPurchase1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPurchase1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPurchase1KeyPressed
    private void sales() {
        panelProduct.setBackground(new Color(0, 51, 153));
        panelPurchase.setBackground(new Color(0, 51, 153));
        panelSales.setBackground(new Color(0, 0, 255));
        panelAccounting.setBackground(new Color(0, 51, 153));
        panelStore.setBackground(new Color(0, 51, 153));
        panelUsers.setBackground(new Color(0, 51, 153));
        panelReport.setBackground(new Color(0, 51, 153));

        panelVisibleController.showPanelWindow(new SubMenuOfPurchase());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnPurchase1;
    private javax.swing.JButton btnSales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelAccounting;
    public static java.awt.Panel panelDisplay;
    private javax.swing.JPanel panelProduct;
    private javax.swing.JPanel panelPurchase;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelReport1;
    private javax.swing.JPanel panelSales;
    private javax.swing.JPanel panelStore;
    private javax.swing.JPanel panelUsers;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
