/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm_products_subPanel;

import Commons.HoverAnimation;
import Commons.PanelController;
import Controller.ProductsController;

/**
 *
 * @author Niklaus
 */
public class ProductsOverview extends javax.swing.JPanel {

    HoverAnimation hover = new HoverAnimation();
    PanelController panelController = new PanelController();
    ProductsController controller = new ProductsController();

    /**
     * Creates new form ProductsOverview
     */
    public ProductsOverview() {
        initComponents();
        lbTotalProductViews.setText(controller.numberOfProduct());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOverview = new javax.swing.JPanel();
        lbtext = new javax.swing.JLabel();
        lbTotalProductViews = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        lbadd = new javax.swing.JLabel();
        panelProducts = new javax.swing.JPanel();
        lbtextProducts = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        panelOverview.setBackground(new java.awt.Color(255, 255, 255));
        panelOverview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 38, 91)));
        panelOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelOverview.setPreferredSize(new java.awt.Dimension(200, 200));

        lbtext.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbtext.setForeground(new java.awt.Color(55, 38, 91));
        lbtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtext.setText("TOTAl Product");

        lbTotalProductViews.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbTotalProductViews.setForeground(new java.awt.Color(55, 38, 91));
        lbTotalProductViews.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalProductViews.setText("4200");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));
        panelAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        panelAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAdd.setPreferredSize(new java.awt.Dimension(94, 47));
        panelAdd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelAddMouseMoved(evt);
            }
        });
        panelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddMouseExited(evt);
            }
        });
        panelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbadd.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbadd.setForeground(new java.awt.Color(55, 38, 91));
        lbadd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/iconsaddproducts.png"))); // NOI18N
        lbadd.setText("Add");
        lbadd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbaddMouseMoved(evt);
            }
        });
        lbadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbaddMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbaddMouseExited(evt);
            }
        });
        panelAdd.add(lbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 90, 47));

        panelProducts.setBackground(new java.awt.Color(255, 255, 255));
        panelProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        panelProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelProducts.setPreferredSize(new java.awt.Dimension(133, 47));
        panelProducts.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelProductsMouseMoved(evt);
            }
        });
        panelProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProductsMouseExited(evt);
            }
        });
        panelProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbtextProducts.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbtextProducts.setForeground(new java.awt.Color(55, 38, 91));
        lbtextProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtextProducts.setText("Products");
        panelProducts.add(lbtextProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 47));

        javax.swing.GroupLayout panelOverviewLayout = new javax.swing.GroupLayout(panelOverview);
        panelOverview.setLayout(panelOverviewLayout);
        panelOverviewLayout.setHorizontalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOverviewLayout.createSequentialGroup()
                        .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOverviewLayout.createSequentialGroup()
                        .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTotalProductViews, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addComponent(lbtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOverviewLayout.setVerticalGroup(
            panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOverviewLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbtext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalProductViews, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(panelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbaddMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbaddMouseMoved
        hover.setHover(panelAdd, lbadd, 18);
    }//GEN-LAST:event_lbaddMouseMoved

    private void panelAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseExited
        hover.releaseHover(panelAdd, lbadd, 16);
    }//GEN-LAST:event_panelAddMouseExited

    private void panelAddMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseMoved
        hover.setHover(panelAdd, lbadd, 18);
    }//GEN-LAST:event_panelAddMouseMoved

    private void panelProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductsMouseExited
        hover.releaseHover(panelProducts, lbtextProducts, 16);
    }//GEN-LAST:event_panelProductsMouseExited

    private void panelProductsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductsMouseMoved
        hover.setHover(panelProducts, lbtextProducts, 18);
        // panelProducts.setBorder(border);
    }//GEN-LAST:event_panelProductsMouseMoved

    private void lbaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbaddMouseExited
        hover.releaseHover(panelAdd, lbadd, 16);
    }//GEN-LAST:event_lbaddMouseExited

    private void lbaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbaddMouseClicked
        panelController.showPanelWindow(new AddProducts());
    }//GEN-LAST:event_lbaddMouseClicked

    private void panelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseClicked

    }//GEN-LAST:event_panelAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTotalProductViews;
    private javax.swing.JLabel lbadd;
    private javax.swing.JLabel lbtext;
    private javax.swing.JLabel lbtextProducts;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelOverview;
    private javax.swing.JPanel panelProducts;
    // End of variables declaration//GEN-END:variables
}
