package Frm_purchase_subpanel;

import Commons.ComboboxDesign;
import Commons.DaynamicDropDownValue;
import Commons.PanelController;
import Commons.TableBackgroundColor;
import Commons.TextPlaceholder;
import Commons.TxtBoxSpace;
import Controller.PurchaseController;
import Frm_products.SubMenuOfPurchase;
import JDialogCustom.ErrorJDialog1;
import JDialogCustom.SuccessJDialog;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import Models.Users;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.plaf.metal.MetalScrollBarUI;
import javax.swing.table.JTableHeader;
import rojerusan.necesario.RSScrollBar;

/**
 *
 * @author world
 */
public class EditStrock_in extends javax.swing.JPanel {

    PanelController panelController = new PanelController();
    DaynamicDropDownValue dynamicDropDownValue = new DaynamicDropDownValue();

    String h = null;
    String serviceAndProduct = null;

    TextPlaceholder placeHolder = new TextPlaceholder();
    TxtBoxSpace txtBoxSpaceing = new TxtBoxSpace();
    PurchaseController controller = new PurchaseController();
    ComboboxDesign comboDesign = new ComboboxDesign();

    String txtSku1 = "Sku or Id";
    String txtQuantity1 = "Quantity";
    String txtPrice1 = "Price";
    String txtDiscout1 = "Discount";
    String txtTotal1 = "Total";
    String txtsellingPrice1 = "Selling Price";
    String txtPaid1 = "Paid";
    String txtDue1 = "Due";
    String txtSearchUser1 = "Name/Mobile/ID";
    String txtPhone1 = "Phone";
    String txtEmail1 = "Email Address";

    public EditStrock_in() {
        initComponents();
        defaultDesign();

        textSpacingMethod();

    }

    private void defaultDesign() {
        dynamicDropDownValue.productItemList(jComboBoxManufacture, "manufacturers");
        dynamicDropDownValue.productItemList(jComboBoxUserRoles, "user_roles");
        comboDesign.comboDesign(jComboBoxManufacture);
        comboDesign.comboDesign(jComboBoxUserRoles);
        jComboBoxUserRoles.setSelectedIndex(1);
        controller.listOfUserInTable(jTableUser, jComboBoxUserRoles.getSelectedItem().toString());
        jScrollPane1.getViewport().setBackground(TableBackgroundColor.UiColors.BACKGROUND_COLOR_WHITE);
        jScrollPane1.getVerticalScrollBar().setUI(new RSScrollBar());

        UserId.setVisible(false);
        lbManufacturerID.setVisible(false);
        lb_id.setVisible(false);
    }

    private void textSpacingMethod() {
        TxtBoxSpace txtBoxSpacing = new TxtBoxSpace();
        txtBoxSpacing.txtBoxSpace(txtSku);
        txtBoxSpacing.txtBoxSpace(txtQuantity);
        txtBoxSpacing.txtBoxSpace(txtPrice);
        txtBoxSpacing.txtBoxSpace(txtDiscout);
        txtBoxSpacing.txtBoxSpace(txtTotal);
        txtBoxSpacing.txtBoxSpace(txtsellingPrice);
        txtBoxSpacing.txtBoxSpace(txtDue);
        txtBoxSpacing.txtBoxSpace(txtSearchUser);

    }

    private void clearField() {
        txtSku.setText("Sku or Id");
        lb_id.setText("");
        txtQuantity.setText("Quantity");
        txtsellingPrice.setText("Selling Price");
        txtPrice.setText("Price");
        txtTotal.setText("Total");
        txtPaid.setText("Paid");
        txtDue.setText("Due");
        txtDiscout.setText("Discount");
        jComboBoxManufacture.setSelectedIndex(0);
    }

    private void calculation(JTextField quantity, JTextField buyingPrice, JTextField discount, JTextField paid) {
        String quantity1 = quantity.getText();
        if (quantity1.equals("Quantity") || quantity1.isEmpty()) {
            quantity1 = "0";
        }

        String buyingPrice1 = buyingPrice.getText();
        if (buyingPrice1.equals("Price") || buyingPrice1.isEmpty()) {
            buyingPrice1 = "0";
        }
        String discount1 = discount.getText();
        if (discount1.equals("Discount") || discount1.isEmpty()) {
            discount1 = "0";
        }
        String paid1 = paid.getText();
        if (paid1.equals("Paid") || paid1.isEmpty()) {
            paid1 = "0";
        }
        double productPurchasePrice = (Double.parseDouble(quantity1) * Double.parseDouble(buyingPrice1))
                - (Double.parseDouble(discount1));
        txtTotal.setText(String.valueOf(productPurchasePrice));

        double dueResult = productPurchasePrice - Double.parseDouble(paid1);
        txtDue.setText(String.valueOf(dueResult));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        txtSearchUser = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxUserRoles = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbimage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtSku = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtDiscout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtsellingPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtDue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxManufacture = new javax.swing.JComboBox<>();
        btnSaved = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        txtPaid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        UserId = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lbManufacturerID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();

        setBackground(java.awt.Color.white);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1formMouseClicked(evt);
            }
        });

        jPanel11.setBackground(java.awt.Color.white);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.black);
        jLabel13.setText("Products Stock entry");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Stock in");

        jPanel14.setBackground(java.awt.Color.white);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchUser.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtSearchUser.setForeground(new java.awt.Color(115, 135, 156));
        txtSearchUser.setText("Name/Mobile/ID");
        txtSearchUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchUserFocusLost(evt);
            }
        });
        txtSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchUserActionPerformed(evt);
            }
        });
        txtSearchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyReleased(evt);
            }
        });
        jPanel14.add(txtSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("User Name/mobile/ID");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 188, 20));

        jComboBoxUserRoles.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jComboBoxUserRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Roles" }));
        jComboBoxUserRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserRolesActionPerformed(evt);
            }
        });
        jComboBoxUserRoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxUserRolesKeyPressed(evt);
            }
        });
        jPanel14.add(jComboBoxUserRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 210, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.black);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Firstly Select User group");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, 24));

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(115, 135, 156));
        txtPhone.setText("Phone");
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel14.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 188, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.black);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Phone Number");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 188, 24));

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(115, 135, 156));
        txtEmail.setText("Email Address");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel14.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 188, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.black);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Email address");
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 188, 24));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/iconsprinter.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorderPainted(false);
        jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 110, 30));

        lbimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/default-Users.png"))); // NOI18N
        lbimage.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153))));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Item");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 31));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantity");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 180, 31));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Purchase Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 200, 31));

        lb6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb6.setForeground(java.awt.Color.black);
        lb6.setText("Manufacturer *");
        jPanel2.add(lb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 140, 30));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 64, -1, -1));

        jPanel12.setBackground(new java.awt.Color(248, 248, 248));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setBorder(null);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSku.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtSku.setForeground(new java.awt.Color(115, 135, 156));
        txtSku.setText("Sku or Id");
        txtSku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSkuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSkuFocusLost(evt);
            }
        });
        txtSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSkuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSkuKeyReleased(evt);
            }
        });
        jPanel10.add(txtSku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jPanel3.setBackground(new java.awt.Color(248, 248, 248));
        jPanel3.setBorder(null);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Quantity :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        txtQuantity.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(115, 135, 156));
        txtQuantity.setText("Quantity");
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jPanel10.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 250, 30));

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));
        jPanel4.setBorder(null);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrice.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(115, 135, 156));
        txtPrice.setText("Price");
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        jPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Price :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        jPanel10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, 30));

        jPanel5.setBackground(new java.awt.Color(248, 248, 248));
        jPanel5.setBorder(null);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiscout.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtDiscout.setForeground(new java.awt.Color(115, 135, 156));
        txtDiscout.setText("Discount");
        txtDiscout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscoutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscoutFocusLost(evt);
            }
        });
        txtDiscout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscoutKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscoutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscoutKeyReleased(evt);
            }
        });
        jPanel5.add(txtDiscout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Discount:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, 30));

        jPanel6.setBackground(new java.awt.Color(248, 248, 248));
        jPanel6.setBorder(null);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(115, 135, 156));
        txtTotal.setText("Total");
        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalFocusLost(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel6.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total :");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        jPanel10.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 250, -1));

        jPanel7.setBackground(new java.awt.Color(248, 248, 248));
        jPanel7.setBorder(null);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsellingPrice.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtsellingPrice.setForeground(new java.awt.Color(115, 135, 156));
        txtsellingPrice.setText("Selling Price");
        txtsellingPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsellingPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsellingPriceFocusLost(evt);
            }
        });
        txtsellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsellingPriceKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsellingPriceKeyPressed(evt);
            }
        });
        jPanel7.add(txtsellingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Selling Price:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, 30));

        jPanel8.setBackground(new java.awt.Color(248, 248, 248));
        jPanel8.setBorder(null);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDue.setEditable(false);
        txtDue.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtDue.setForeground(new java.awt.Color(115, 135, 156));
        txtDue.setText("Due");
        txtDue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDueFocusLost(evt);
            }
        });
        jPanel8.add(txtDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Due :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        jPanel10.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 210, -1));

        jComboBoxManufacture.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jComboBoxManufacture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Manufacturer" }));
        jComboBoxManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxManufactureActionPerformed(evt);
            }
        });
        jComboBoxManufacture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxManufactureKeyPressed(evt);
            }
        });
        jPanel10.add(jComboBoxManufacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 210, 30));

        btnSaved.setBackground(new java.awt.Color(0, 51, 153));
        btnSaved.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSaved.setForeground(new java.awt.Color(250, 255, 255));
        btnSaved.setText("Submit");
        btnSaved.setAlignmentY(0.0F);
        btnSaved.setBorderPainted(false);
        btnSaved.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaved.setOpaque(true);
        btnSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavedActionPerformed(evt);
            }
        });
        jPanel10.add(btnSaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 140, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 10, 160));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 10, 160));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 10, 160));

        jPanel9.setBackground(new java.awt.Color(248, 248, 248));
        jPanel9.setBorder(null);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPaid.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtPaid.setForeground(new java.awt.Color(115, 135, 156));
        txtPaid.setText("Paid");
        txtPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaidFocusLost(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaidKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
        });
        jPanel9.add(txtPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 150, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total Paid :");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 250, 30));

        lb_id.setText("ID:");
        jPanel10.add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 150, 30));

        UserId.setText("U_ID");
        jPanel10.add(UserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 51, 153));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(250, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/iconsback.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.setAlignmentY(0.0F);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setIconTextGap(14);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel10.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 30));

        lbManufacturerID.setText("M_ID");
        jPanel10.add(lbManufacturerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jTableUser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Ref", "Debit", "Credit", "Due", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableUser.setGridColor(java.awt.Color.white);
        jTableUser.setName("User Table"); // NOI18N
        jTableUser.setRowHeight(28);
        jTableUser.setSelectionBackground(new java.awt.Color(0, 51, 153));
        jTableUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableUser.setShowVerticalLines(false);
        jTableUser.getTableHeader().setReorderingAllowed(false);
        jTableUser.setUpdateSelectionOnSort(false);
        jTableUser.setVerifyInputWhenFocusTarget(false);
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUser);
        if (jTableUser.getColumnModel().getColumnCount() > 0) {
            jTableUser.getColumnModel().getColumn(0).setResizable(false);
            jTableUser.getColumnModel().getColumn(1).setResizable(false);
            jTableUser.getColumnModel().getColumn(2).setResizable(false);
            jTableUser.getColumnModel().getColumn(3).setResizable(false);
            jTableUser.getColumnModel().getColumn(4).setResizable(false);
            jTableUser.getColumnModel().getColumn(5).setResizable(false);
            jTableUser.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 950, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSkuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSkuFocusGained
        placeHolder.placeHolder(txtSku1, txtSku);
    }//GEN-LAST:event_txtSkuFocusGained

    private void txtSkuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSkuFocusLost
        placeHolder.placeHolder(txtSku1, txtSku);
    }//GEN-LAST:event_txtSkuFocusLost

    private void txtSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkuKeyPressed
        if (evt.getKeyCode() == evt.VK_DOWN) {
     

        }
        if (evt.getKeyCode() == evt.VK_ENTER) {

            txtQuantity.requestFocus();

        }
    }//GEN-LAST:event_txtSkuKeyPressed

    private void txtSkuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkuKeyReleased
      
    }//GEN-LAST:event_txtSkuKeyReleased

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        placeHolder.placeHolder(txtQuantity1, txtQuantity);
    }//GEN-LAST:event_txtQuantityFocusGained

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        placeHolder.placeHolder(txtQuantity1, txtQuantity);
    }//GEN-LAST:event_txtQuantityFocusLost

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtPrice.requestFocus();
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        calculation(txtQuantity, txtPrice, txtDiscout, txtPaid);

    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        placeHolder.placeHolder(txtPrice1, txtPrice);
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        placeHolder.placeHolder(txtPrice1, txtPrice);
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtDiscout.requestFocus();
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        calculation(txtQuantity, txtPrice, txtDiscout, txtPaid);
    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtDiscoutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscoutFocusGained
        placeHolder.placeHolder(txtDiscout1, txtDiscout);
    }//GEN-LAST:event_txtDiscoutFocusGained

    private void txtDiscoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscoutFocusLost
        placeHolder.placeHolder(txtDiscout1, txtDiscout);
    }//GEN-LAST:event_txtDiscoutFocusLost

    private void txtDiscoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscoutKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtsellingPrice.requestFocus();
        }
    }//GEN-LAST:event_txtDiscoutKeyPressed

    private void txtDiscoutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscoutKeyReleased
        calculation(txtQuantity, txtPrice, txtDiscout, txtPaid);
    }//GEN-LAST:event_txtDiscoutKeyReleased

    private void txtDiscoutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscoutKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDiscoutKeyTyped

    private void txtTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalFocusGained
        placeHolder.placeHolder(txtTotal1, txtTotal);
    }//GEN-LAST:event_txtTotalFocusGained

    private void txtTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalFocusLost
        placeHolder.placeHolder(txtTotal1, txtTotal);
    }//GEN-LAST:event_txtTotalFocusLost

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtsellingPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsellingPriceFocusGained
        placeHolder.placeHolder(txtsellingPrice1, txtsellingPrice);
    }//GEN-LAST:event_txtsellingPriceFocusGained

    private void txtsellingPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsellingPriceFocusLost
        placeHolder.placeHolder(txtsellingPrice1, txtsellingPrice);
    }//GEN-LAST:event_txtsellingPriceFocusLost

    private void txtsellingPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsellingPriceKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtPaid.requestFocus();
        }
    }//GEN-LAST:event_txtsellingPriceKeyPressed

    private void txtsellingPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsellingPriceKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtsellingPriceKeyTyped

    private void txtDueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDueFocusGained
        placeHolder.placeHolder(txtDue1, txtDue);
    }//GEN-LAST:event_txtDueFocusGained

    private void txtDueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDueFocusLost
        placeHolder.placeHolder(txtDue1, txtDue);
    }//GEN-LAST:event_txtDueFocusLost

    private void jComboBoxManufactureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxManufactureKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnSaved.requestFocus();
        }
    }//GEN-LAST:event_jComboBoxManufactureKeyPressed

    private void btnSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavedActionPerformed
        HashMap<String, String> defaultField = new HashMap<>();
        int i = 0;

        String userId = UserId.getText();
        if (userId.equals("null") || userId.equals("U_ID")) {
            userId = null;
        }

        String quantity = txtQuantity.getText();
        if (quantity.equals("Quantity")) {
            quantity = "0";
            i += 1;
        }
        String selling_price = txtsellingPrice.getText();
        if (selling_price.equals("Selling Price")) {
            selling_price = "0";
            i += 1;
        }
        String purchase_price = txtPrice.getText();
        if (purchase_price.equals("Price")) {
            purchase_price = "0";
            i += 1;
        }

        String purchase_amount = txtTotal.getText();
        if (purchase_amount.equals("Total")) {
            purchase_amount = "0";
            i += 1;
        }
        String purchase_paid = txtPaid.getText();
        if (purchase_paid.equals("Paid")) {
            purchase_paid = "0";
            i += 1;
        }
        String purchase_due = txtDue.getText();
        if (purchase_due.equals("Due")) {
            purchase_due = "0";
            i += 1;
        }
        String in_payment_complate = "No";
        if (purchase_due.equals("0")) {
            in_payment_complate = "Yes";
        }
        String purchase_discount = txtDiscout.getText();
        if (purchase_discount.equals("Discount")) {
            purchase_discount = "0";
            i += 1;
        }

        String purchase_manufacturer = jComboBoxManufacture.getSelectedItem().toString();
        if (purchase_manufacturer.equals("Select Manufacturer")) {
            purchase_manufacturer = "0";
            i += 1;
        } else {
            purchase_manufacturer = lbManufacturerID.getText();
        }

        defaultField.put("userId", userId);
        defaultField.put("product_id", lb_id.getText());
        defaultField.put("quantity", quantity);
        defaultField.put("selling_price", selling_price);
        defaultField.put("purchase_price", purchase_price);
        defaultField.put("purchase_amount", purchase_amount);
        defaultField.put("purchase_paid", purchase_paid);
        defaultField.put("purchase_due", purchase_due);
        defaultField.put("purchase_discount", purchase_discount);
        defaultField.put("purchase_manufacturer", purchase_manufacturer);
        defaultField.put("in_paid_ac", "");
        defaultField.put("in_payment_complate", in_payment_complate);

//        if (!txtSku.equals("Sku or Id")) {
//            if (controller.addProduct(defaultField) == true) {
//                SuccessJDialog er = new SuccessJDialog(null, true);
//                er.setVisible(true);
//                clearField();
//            } else {
//                ErrorJDialog1 er = new ErrorJDialog1(null, true);
//                er.setVisible(true);
//            }
//        } else {
//            ErrorJDialog1 er = new ErrorJDialog1(null, true);
//            er.setVisible(true);
//        }
    }//GEN-LAST:event_btnSavedActionPerformed

    private void txtPaidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusGained
        placeHolder.placeHolder(txtPaid1, txtPaid);
    }//GEN-LAST:event_txtPaidFocusGained

    private void txtPaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusLost
        placeHolder.placeHolder(txtPaid1, txtPaid);
    }//GEN-LAST:event_txtPaidFocusLost

    private void txtPaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jComboBoxManufacture.requestFocus();
        }
    }//GEN-LAST:event_txtPaidKeyPressed

    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased
        calculation(txtQuantity, txtPrice, txtDiscout, txtPaid);
    }//GEN-LAST:event_txtPaidKeyReleased

    private void txtPaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPaidKeyTyped

    private void jPanel1formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseClicked
       
    }//GEN-LAST:event_jPanel1formMouseClicked

    private void jComboBoxManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxManufactureActionPerformed
        String manuf_id = dynamicDropDownValue.getComboboxGroupId("manufacturers", jComboBoxManufacture.getSelectedItem().toString());
        lbManufacturerID.setText(manuf_id);
    }//GEN-LAST:event_jComboBoxManufactureActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        panelController.showPanelWindow(new SubMenuOfPurchase());
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchUserFocusGained
        placeHolder.placeHolder(txtSearchUser1, txtSearchUser);
    }//GEN-LAST:event_txtSearchUserFocusGained

    private void txtSearchUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchUserFocusLost
        placeHolder.placeHolder(txtSearchUser1, txtSearchUser);
    }//GEN-LAST:event_txtSearchUserFocusLost

    private void txtSearchUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyPressed
        String searchBox = txtSearchUser.getText();
        if (searchBox.equals("Name/Mobile/ID") || searchBox.isEmpty()) {
            searchBox = "";
        }
        controller.SearchByUserInfo(jTableUser, txtSearchUser.getText(), jComboBoxUserRoles.getSelectedItem().toString());

    }//GEN-LAST:event_txtSearchUserKeyPressed

    private void txtSearchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserKeyReleased

    private void jComboBoxUserRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserRolesActionPerformed
        Object UserRoles = jComboBoxUserRoles.getSelectedItem();
        controller.listOfUserInTable(jTableUser, UserRoles);
    }//GEN-LAST:event_jComboBoxUserRolesActionPerformed

    private void jComboBoxUserRolesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxUserRolesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserRolesKeyPressed

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        placeHolder.placeHolder(txtPhone1, txtPhone);
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        placeHolder.placeHolder(txtPhone1, txtPhone);
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        placeHolder.placeHolder(txtEmail1, txtEmail);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        placeHolder.placeHolder(txtEmail1, txtEmail);
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserActionPerformed

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        int i = jTableUser.getSelectedRow();
        TableModel table = jTableUser.getModel();
        String id = table.getValueAt(i, 0).toString();
        String name = table.getValueAt(i, 1).toString();
        String email = table.getValueAt(i, 3).toString();
        String phone = table.getValueAt(i, 4).toString();

        UserId.setText(id);
        Users userModel = controller.singleUserPicker(id);
        lbimage.setText("");
        lbimage.setIcon(null);
        try {

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(userModel.getImage()).getImage().getScaledInstance(70, 60, Image.SCALE_SMOOTH));
            lbimage.setIcon(imageIcon);
        } catch (Exception e) {
            System.out.println("image Exception :" + e);
            lbimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/default-Users.png")));
        }

        txtSearchUser.setText(name);
        txtEmail.setText(email);
        txtPhone.setText(phone);

    }//GEN-LAST:event_jTableUserMouseClicked
    private void cleanUser() {
        txtSearchUser.setText(txtSearchUser1);
        txtEmail.setText(txtEmail1);
        txtPhone.setText(txtPhone1);
        jComboBoxUserRoles.setSelectedIndex(1);
        lbimage.setText("");
        lbimage.setIcon(null);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("/IconImage/default-Users.png").getImage().getScaledInstance(70, 60, Image.SCALE_SMOOTH));
        lbimage.setIcon(imageIcon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserId;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaved;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxManufacture;
    private javax.swing.JComboBox<String> jComboBoxUserRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableUser;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lbManufacturerID;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lbimage;
    private javax.swing.JTextField txtDiscout;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchUser;
    private javax.swing.JTextField txtSku;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtsellingPrice;
    // End of variables declaration//GEN-END:variables
}
