/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frm_purchase_subpanel;

import Commons.ComboboxDesign;
import Commons.DateFormating;
import Commons.DaynamicDropDownValue;
import Commons.PanelController;
import Commons.TableBackgroundColor;
import Commons.TextPlaceholder;
import Commons.TxtBoxSpace;
import Controller.PurchaseController;
import JDialogCustom.ErrorJDialog1;
import JDialogCustom.SuccessJDialog;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author world
 */
public class PurchasesCustom extends javax.swing.JPanel {

    PanelController panelController = new PanelController();
    TextPlaceholder placeHolder = new TextPlaceholder();
    TxtBoxSpace txtBoxSpaceing = new TxtBoxSpace();
    PurchaseController controller = new PurchaseController();
    ComboboxDesign comboDesign = new ComboboxDesign();
    DaynamicDropDownValue dropDownValues = new DaynamicDropDownValue();

    String txtSearch1 = "Search";

    /**
     * Creates new form Purchases
     */
    public PurchasesCustom() {
        initComponents();
        controller.allPurchaseReport(jTable_list);
        defaultDesign();
        Jpanel_list.setVisible(false);
    }

    private void defaultDesign() {
        comboDesign.comboDesign(jComboBoxItemStatus);
        jTable_list.setBackground(Color.WHITE);
        jScrollPane1.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getViewport().setBackground(TableBackgroundColor.UiColors.BACKGROUND_COLOR_WHITE);
    }

//    private void defaultListOfTable() {
//        if (jComboBoxManufacture.getSelectedItem().equals("Select Manufacturer")
//                && jComboBoxChooseVendor.getSelectedItem().equals("Select Vendor")
//                && jComboBoxUnite.getSelectedItem().equals("Select Units")
//                && jComboBoxItemStatus.getSelectedItem().equals("Select Status")
//                && (txtSearch.getText().equals("Search") || txtSearch.getText().isEmpty())) {
//            controller.allPurchaseReport(jTable_list);
//
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lb9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lb7 = new javax.swing.JLabel();
        jComboBoxItemStatus = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        Jpanel_list = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_list = new javax.swing.JTable();

        setBackground(java.awt.Color.white);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(78, 78, 78));
        jLabel17.setText("Purchase products");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1000, 10));

        jPanel2.setBackground(java.awt.Color.white);

        jPanel4.setBackground(java.awt.Color.white);

        txtSearch.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(115, 135, 156));
        txtSearch.setText("Search");
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        txtSearch.setPreferredSize(new java.awt.Dimension(60, 16));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lb9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lb9.setForeground(new java.awt.Color(78, 78, 78));
        lb9.setText("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(java.awt.Color.white);

        lb7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lb7.setForeground(new java.awt.Color(78, 78, 78));
        lb7.setText("Status");

        jComboBoxItemStatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBoxItemStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jComboBoxItemStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.Color.white);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setText("Report");
        jButton2.setAlignmentX(0.5F);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lb10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lb10.setForeground(new java.awt.Color(78, 78, 78));
        lb10.setText("End Date");

        lb11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lb11.setForeground(new java.awt.Color(78, 78, 78));
        lb11.setText("Start Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb10)
                    .addComponent(lb11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout Jpanel_listLayout = new javax.swing.GroupLayout(Jpanel_list);
        Jpanel_list.setLayout(Jpanel_listLayout);
        Jpanel_listLayout.setHorizontalGroup(
            Jpanel_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        Jpanel_listLayout.setVerticalGroup(
            Jpanel_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_listLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(Jpanel_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 153, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable_list.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable_list.setForeground(new java.awt.Color(51, 51, 51));
        jTable_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer", "Company Name", "Due", "Paid", "Total", "Payment Status", "Sent Acc", "VIEW", "DELETE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_list.setGridColor(new java.awt.Color(204, 204, 204));
        jTable_list.setRowHeight(40);
        jTable_list.setRowSelectionAllowed(false);
        jTable_list.setSelectionBackground(new java.awt.Color(102, 182, 247));
        jTable_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_list);
        if (jTable_list.getColumnModel().getColumnCount() > 0) {
            jTable_list.getColumnModel().getColumn(0).setResizable(false);
            jTable_list.getColumnModel().getColumn(1).setResizable(false);
            jTable_list.getColumnModel().getColumn(2).setResizable(false);
            jTable_list.getColumnModel().getColumn(3).setResizable(false);
            jTable_list.getColumnModel().getColumn(4).setResizable(false);
            jTable_list.getColumnModel().getColumn(5).setResizable(false);
            jTable_list.getColumnModel().getColumn(6).setResizable(false);
            jTable_list.getColumnModel().getColumn(7).setResizable(false);
            jTable_list.getColumnModel().getColumn(8).setResizable(false);
            jTable_list.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1000, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        placeHolder.placeHolder(txtSearch1, txtSearch);
        //   defaultListOfTable();
        if (txtSearch.getText().equals(null) || txtSearch.getText().equals("Search")) {
            Jpanel_list.setVisible(false);

        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        placeHolder.placeHolder(txtSearch1, txtSearch);
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        controller.FilterBysearchField(txtSearch.getText(), jTable_list);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (!txtSearch.getText().isEmpty() || !txtSearch.getText().equals("Search")) {
            Jpanel_list.setVisible(true);

        } else {
            //  defaultListOfTable();
        }
        controller.dataSearchFilter(txtSearch.getText(), jTable1);
    }//GEN-LAST:event_txtSearchKeyPressed

    private void jComboBoxItemStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemStatusActionPerformed
        String name = jComboBoxItemStatus.getSelectedItem().toString();
        Jpanel_list.setVisible(false);
        if (name.equals("Select Status")) {

        } else {
            // JOptionPane.showMessageDialog(null, name);
        }
    }//GEN-LAST:event_jComboBoxItemStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jpanel_list.setVisible(false);

        DateFormating formateDate = new DateFormating();
        String status = jComboBoxItemStatus.getSelectedItem().toString();

        String StartDate = null;
        if (jDateChooser1.getDate() != null) {
            StartDate = formateDate.dateFormate(jDateChooser1.getDate()).concat(" 00:00:00");
            
        }

        String EndDate = null;
        if (jDateChooser2.getDate() != null) {
            EndDate = formateDate.dateFormate(jDateChooser2.getDate()).concat(" 23:00:00");
        } else {
            EndDate = formateDate.dateFormate(new Date()).concat("23:00:00");
        }

        String txtSearch1 = txtSearch.getText();
        if (txtSearch1.equals("Search")) {
            txtSearch1 = null;
        }
        
        String sql = null;
        if (txtSearch1 != null && StartDate == null) {
            sql = "Select ins.id,u.username,u.company,ins.due,ins.paid,ins.totalPrice,ins.date,ins.payment_complate,ins.isSent_Account,ins.inventory_unique_id FROM `inventory_summary` as ins,users as u WHERE "
                    + "ins.status='" + status + "' AND u.id=ins.customerId AND (u.username like '%" + txtSearch1 + "%'OR u.company "
                    + " LIKE '%" + txtSearch1 + "%' OR u.phone='" + txtSearch1 + "' ) order by ins.date DESC limit 20";
        } else if (txtSearch1 != null && StartDate != null) {
            sql = "Select ins.id,u.username,u.company,ins.due,ins.paid,ins.totalPrice,ins.date,ins.payment_complate,ins.isSent_Account,ins.inventory_unique_id FROM `inventory_summary` as ins,users as u WHERE ins.status='Active' "
                    + "AND u.id=ins.customerId AND (u.username like '%" + txtSearch1 + "%'OR u.company "
                    + " LIKE '%" + txtSearch1 + "%' OR u.phone='" + txtSearch1 + "'  "
                    + "AND ins.date BETWEEN '" + StartDate + "' and '" + EndDate + "') order by ins.Date DESC Limit 20";
        } else if (StartDate != null && txtSearch1 == null) {
            sql = "Select ins.id,u.username,u.company,ins.due,ins.paid,ins.totalPrice,ins.date,ins.payment_complate,ins.isSent_Account,ins.inventory_unique_id from `inventory_summary` as ins,users as u WHERE ins.status='Active' "
                    + "AND u.id=ins.customerId AND  ins.date BETWEEN '" + StartDate + "' and '" + EndDate + "' order by ins.Date DESC limit 20";
        }else{
             sql = "Select ins.id,u.username,u.company,ins.due,ins.paid,ins.totalPrice,ins.date,ins.payment_complate,ins.isSent_Account,ins.inventory_unique_id from `inventory_summary` as ins,users as u WHERE ins.status='Active' "
                    + "AND u.id=ins.customerId order by ins.Date DESC limit 20";
       
        }
        // System.out.println(sql);
        System.out.println(sql);
        controller.PurchaseSearch(sql, jTable_list);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.reportGenerator(jTable_list);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel table = jTable1.getModel();
        String productName = table.getValueAt(i, 1).toString();
        txtSearch.setText(productName);
        controller.FilterBysearchField(productName, jTable_list);
        Jpanel_list.setVisible(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_listMouseClicked

        //JOptionPane.showMessageDialog(null, table.getValueAt(i, 0));
        Jpanel_list.setVisible(false);

        int column = jTable_list.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTable_list.getRowHeight();

        if (row < jTable_list.getRowCount() && row >= 0 && column < jTable_list.getColumnCount() && column >= 0) {

            Object value = jTable_list.getValueAt(row, column);

            if (value instanceof JButton) {
                ((JButton) value).doClick();

                JButton button = (JButton) value;

                if (button.getName().equals("Acc")) {

                    System.out.println("Acc");
                } else if (!button.getName().equals("Acc")) {
                    System.out.println("EDIT");
                    int i = jTable_list.getSelectedRow();
                    TableModel table = jTable_list.getModel();
                    String due = table.getValueAt(i, 3).toString();
                    String paid = table.getValueAt(i, 4).toString();
                    String fullTotal = table.getValueAt(i, 5).toString();
                    System.out.println(button.getName());
                    panelController.showPanelWindow(new Strock_in_Custom(button.getName(), due, paid, fullTotal));
//                    if (controller.deactiveProduct("inventory", button.getName()) == true) {
//                        SuccessJDialog er = new SuccessJDialog(null, true);
//                        er.setVisible(true);
//                        controller.allPurchaseReport(jTable_list);
//                    } else {
//                        ErrorJDialog1 er = new ErrorJDialog1(null, true);
//                        er.setVisible(true);
//                    }
                }
            }
        }
    }//GEN-LAST:event_jTable_listMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Jpanel_list.setVisible(false);
        //    defaultListOfTable();
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxItemStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_list;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb9;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
